name: Terraform Terratest with Go

on:
  push:
    branches:
      - feature/terra-test-go-lang

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::884360309640:role/arc-iac-oidc-github-role
          aws-region: us-east-1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Create test directory and download go from S3
        run: |
          mkdir -p test-directory
          aws s3 cp s3://arc-iac-go-lang-terraform-terra-test/example_test.go test-directory/example_test.go

      - name: Initialize Go module and install dependencies
        run: |
          cd test-directory
          ls
          go mod init terraform-test || true
          go get github.com/gruntwork-io/terratest/modules/terraform
          go get github.com/stretchr/testify/assert
          go mod tidy
          go test -v -timeout 0

